# Generated by Django 5.1.6 on 2025-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.IntegerField(default=154533, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
