# Generated by Django 5.1.6 on 2025-03-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmodel',
            name='tax_percentage',
        ),
    ]
