# Generated by Django 5.1.6 on 2025-03-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesmodel_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
