# Generated by Django 5.1.6 on 2025-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=70124563, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
